# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8940a6b776fb870418be412b470c3b73e7880081ffe650e71b9a62689b849f3f84ad1dec7e59af1b055f8dcd15ede2383130f7a168d001312b0b8e145babdc18

test:
  secret_key_base: 486eb93bc6afc427329d7b9399c1b4613a9642fbedd91f7abdaf1e2ef0a287b884ecaa4c6a19fdbbfaa64d99b8616b8a3964d76a20b859a7578dea8954a6913b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
